name: 'BundleBudget'
description: 'Check if bundle has exceeded allocated size budget'
inputs:
  appPath:
    description: 'Path to the meteor app'
    required: true
  buildDir: 
    description: :'build folder name'
    required: true
  bundleBudget:  
    description: 'Size budget for bundle in bytes'
    required: true
outputs:
  status:
    description: 'Status of app bundle'
  message:
    description: 'Message to send further'
runs:
  using: 'node12'
  main: 'index.js'